name: Publish Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    name: Build Docker image and push to repositories

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Project Dependancies
        run: |
          composer install
          npm install
      - name: Build Javascript Assets
        run: |
          npm run prod

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./
          push: true
          # Note: tags has to be all lower-case
          tags: |
            ghcr.io/stacktonic/ubuntu:latest
            ghcr.io/stacktonic/ubuntu:${{ steps.vars.outputs.tag }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Create a Release
        uses: elgohr/Github-Release-Action@master
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          args: ${{ github.event.head_commit.message }}